name: Deploy Usuarios

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Actualizar código
        run: |
          cd /home/ubuntu/Prueba3Java
          git pull origin main

      - name: Verificar Docker Compose
        run: |
          cd /home/ubuntu/Prueba3Java
          ls -l docker-compose.yml
          docker compose config

      - name: Reconstruir y levantar usuarios
        run: |
          cd /home/ubuntu/Prueba3Java
          docker compose up -d --build usuarios
