name: Deploy Usuarios

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # Usa tu servidor EC2 Ubuntu

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar proyecto con Maven
        working-directory: ./UsuarioEcommerce-main/UsuarioEcommerce-main/usuarios/usuarios
        run: mvn clean package -DskipTests

      - name: Crear paquete ZIP optimizado para AWS Lambda
        working-directory: ./UsuarioEcommerce-main/UsuarioEcommerce-main/usuarios/usuarios
        run: |
          cd target
          mkdir -p lambda_package
          unzip -q *.jar -d lambda_package/
          cd lambda_package
          zip -r ../lambda_deploy.zip .

      - name: Subir a Amazon S3 y Actualizar Lambda
        working-directory: ./UsuarioEcommerce-main/UsuarioEcommerce-main/usuarios/usuarios
        run: |
          BUCKET_NAME="bucket-deploy-usuarios-emanuel"
          
          echo "1. Subiendo el archivo ZIP pesado a Amazon S3..."
          aws s3 cp target/lambda_deploy.zip s3://$BUCKET_NAME/lambda_deploy.zip --region us-east-1
          
          echo "2. Actualizando la Lambda apuntando al archivo en S3..."
          aws lambda update-function-code \
            --function-name deploy-usuarios-lambda \
            --s3-bucket $BUCKET_NAME \
            --s3-key lambda_deploy.zip \
            --region us-east-1